import { Inter } from "next/font/google";
import Head from "next/head";
import { FC, ReactNode } from "react";
import Navbar from "./navbar";
import css from "./layout.module.css";

type Props = {
  children: ReactNode;
};

const inter = Inter({ subsets: ["latin"] });

const Layout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Nasa Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🛰️</text></svg>"
        ></link>
      </Head>
      <div className={`${css.root} bg-dark-200 min-h-screen text-white`}>
        <Navbar />
        {children}
      </div>
    </>
  );
};

export default Layout;
